global:
  scrape_interval: 10s

scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['127.0.0.1:9090']

  - job_name: 'actuator_demo_app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
#      - targets: ['HOST_IP:8080']
      - targets: ['192.168.0.155:8080']
